name: Deploy Laravel to cPanel via SSH

on:
  push:
    branches:
      - master  # Ubah jika pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, xml, ctype, json, tokenizer, pdo, openssl

      - name: Install Composer dependencies
        run:  composer install --no-dev --optimize-autoloader --no-scripts

      - name: Upload files to cPanel via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CPANEL_SSH_HOST }}
          username: ${{ secrets.CPANEL_SSH_USER }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."                      # semua file
          target: "public_html/vms.gen-zi.id"
          overwrite: true
          strip_components: 1              # penting agar tidak mengirim ke subfolder ./source-root

      - name: Run Laravel deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_SSH_HOST }}
          username: ${{ secrets.CPANEL_SSH_USER }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          debug: true
          script: |
            echo "Connected to $(hostname)"
            cd public_html/vms.gen-zi.id || { echo "Target folder not found"; exit 1; }
            echo "Current directory:"
            pwd
            echo "Checking artisan file:"
            ls -l artisan

            # Run Laravel optimizations
            /usr/local/bin/ea-php82 artisan migrate --force || echo "Migration failed"
            /usr/local/bin/ea-php82 artisan config:cache || echo "Config cache failed"
            /usr/local/bin/ea-php82 artisan route:cache || echo "Route cache failed"
