name: Deploy Application

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1

        - name: Install Composer Dependencies
          run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

        - name: Install Node JS
          uses: actions/setup-node@v3
          with: 
            node-version: '20'

        - name: Install NPM Dependencies
          run: npm install

        - name: Build NPM Asset
          run: npm run

        - name: Synchronize Files to Server
          uses: easingthemes/ssh-deploy@v2.1.5
          env: 
            SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }} 
            SOURCE: "."
            REMOTE_HOST: ${{ secrets.CPANEL_SSH_HOST }}
            REMOTE_USER: ${{ secrets.CPANEL_SSH_USER }}
            REMOTE_PORT: ${{ secrets.SSH_PORT }}
            TARGET: "/home/gens7193/public_html/vms.gen-zi.id"

        - name: Run Remote/Artisan Commands
          uses: appleboy/ssh-action@v0.1.6
          with: 
            host: ${{ secrets.CPANEL_SSH_HOST }}
            port: ${{ secrets.SSH_PORT }}
            username: ${{ secrets.CPANEL_SSH_USER }}
            key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
            script: |
                cd /home/gens7193/public_html/vms.gen-zi.id
                php artisan migrate --force
                php artisan optimize